version: '3'

services:
  web:
    build: ./docker/web
    container_name: web
    environment:
      TZ: "Asia/Tokyo"
    ports:
      - "80:80"
    volumes:
      - ./batch:/udemy/batch
      - ./app:/udemy/app
    depends_on:
      - db

  db:
    build: ./docker/db
    platform: linux/amd64
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - 3306:3306
    volumes:
      - "./docker/db/data:/var/lib/mysql"
      - "./docker/db/init:/docker-entrypoint-initdb.d"
      - "./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf"
    restart: always
